using NUnit.Framework;
using Customer_Ticketing_System.Models;
using Customer_Ticketing_System.Services;
using System.Threading.Tasks;

namespace Customer_Ticketing_System.Tests
{
    [TestFixture]
    public class EdgeCaseTests
    {
        private TicketService service;

        [SetUp]
        public void Setup()
        {
            service = new TicketService();
        }

        [Test]
        public async Task CreatingDuplicateTickets_ShouldAllowSinceIdIsAutoGenerated()
        {
            var customer = new Customer("Eve", "eve@example.com");

            var t1 = await service.CreateTicketAsync("Issue", "Same desc", customer);
            var t2 = await service.CreateTicketAsync("Issue", "Same desc", customer);

            Assert.AreNotEqual(t1.TicketId, t2.TicketId);
        }
    }
}
